[[permission]]
identifier = "allow-open-themes-folder"
description = "Allow opening themes folder"
commands.allow = ["open_themes_folder"]

[[permission]]
identifier = "allow-open-soundpacks-folder"
description = "Allow opening soundpacks folder"
commands.allow = ["open_soundpacks_folder"]

[[permission]]
identifier = "allow-load-media-library-state"
description = "Allow loading persisted media library state"
commands.allow = ["load_media_library_state"]
